name: Python CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r services/data_proxy/requirements.txt -r bots/telegram_feedback_bot/requirements.txt -r algorithms/forecasting/requirements.txt
          pip install black ruff pytest
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Tests
        run: pytest -q
